.github/workflows/ci.yml, poetry.lock, pyproject.toml, src/mds/app.py, tests/conftest.py, tests/test_server.py
* also stop pushing to Quay.io
* updated dependencies
* don't send coverage report in PR
* add tests for wait-for-db
* Add `/_status` health check point
=> Add `/_status` health check endpoint

src/mds/maintain.py, src/mds/query.py, tests/test_maintain.py, tests/test_query.py
* add shallow merge option to metadata update
* fixed wrong document about max limit in metadata query
* allow slashes in GUID
=> add shallow merge option to metadata update

.codacy.yml, .github/workflows/ci.yml, .secrets.baseline, README.md
* Update GitHub actions to use Coveralls rather than Codacy
=> fix(actions): use Coveralls rather than Codacy

docs/openapi.yaml, src/mds/objects.py, tests/test_objects.py
- add DELETE /objects/{guid} endpoint to delete indexd and metadata records
=> (PXP-5530): Add DELETE /objects/{guid} endpoint 

.github/workflows/ci.yml, poetry.lock, pyproject.toml, src/mds/agg_mds/mds.py, src/mds/agg_mds/redis_cache.py, src/mds/main.py, src/mds/populate.py, tests/config.json, tests/conftest.py, tests/test_agg_mds_commons.py, tests/test_agg_mds_mds.py, tests/test_agg_mds_query.py, tests/test_agg_mds_redis_cache.py, tests/test_populate.py
* Tests for aggregate metadata APIs
=> feat(aggregation-tests): tests for aggregation API

.github/workflows/ci.yml, .secrets.baseline, Dockerfile, README.md, configs/brh_config.json, docker-compose.yml, poetry.lock, pyproject.toml, src/mds/agg_mds/__init__.py, src/mds/agg_mds/commons.py, src/mds/agg_mds/mds.py, src/mds/agg_mds/query.py, src/mds/agg_mds/redis_cache.py, src/mds/config.py, src/mds/main.py, src/mds/populate.py, tests/config.json, tests/conftest.py, tests/test_agg_mds_commons.py, tests/test_agg_mds_mds.py, tests/test_agg_mds_query.py, tests/test_agg_mds_redis_cache.py, tests/test_populate.py
Merge the https://github.com/uc-cdis/agg-metadata/ files to a feature branch
* Add aggregate APIs to the MDS for ecosystems porting functionality from https://github.com/uc-cdis/agg-metadata/
=> feat(aggregate-data): APIs for aggregate metadata

configs/brh_config.json, src/mds/agg_mds/commons.py, src/mds/agg_mds/query.py, src/mds/agg_mds/redis_cache.py, src/mds/populate.py, tests/config.json, tests/test_agg_mds_commons.py, tests/test_agg_mds_query.py, tests/test_agg_mds_redis_cache.py, tests/test_populate.py
Jira Ticket: [PXP-7954](https://ctds-planx.atlassian.net/browse/PXP-7954)
* Pull in changes from https://github.com/uc-cdis/agg-metadata/pull/9
=> feat(field-and-summ): field mapping changes

.github/workflows/ci.yml, docker-compose.yml, postgres-init/init.sh, src/mds/agg_mds/datastore/__init__.py, src/mds/agg_mds/datastore/redis_cache.py, src/mds/agg_mds/query.py, src/mds/config.py, src/mds/main.py, src/mds/populate.py, tests/conftest.py, tests/test_agg_mds_datastore.py, tests/test_agg_mds_query.py, tests/test_agg_mds_redis_cache.py, tests/test_populate.py
* Optimize how we map fields. Do it once on import and not on subsequent loads
* Create a layer of abstraction away from redis
* Make local credentials consistent with what we use in `compose-services`
=> feat(api-updates): update mappings

pyproject.toml, src/mds/agg_mds/adapters.py, src/mds/agg_mds/commons.py, src/mds/agg_mds/mds.py, src/mds/populate.py, tests/test_agg_mds_adapters.py, tests/test_agg_mds_mds.py
Jira Ticket: [HP-508](https://ctds-planx.atlassian.net/browse/HP-508 )
This fixes an issue that prevents populating a AggMDS if one or more of the remote commons is down or unavailable. Instead of throwing an exception, the error is logged and the remote commons is skipped. 
* More verbose logging for populate
* Timeout retry via tenacity
* Python package: tenacity
=> Feat tenacity

README.md, docker-compose.yml, docs/openapi.yaml, poetry.lock, pyproject.toml, src/mds/config.py, src/mds/populate.py, tests/test_agg_mds_elasticsearch_dao.py
Jira Ticket: [HP-287](https://ctds-planx.atlassian.net/browse/HP-287)
* Use env and config for populate script rather than passing parameters
* Better name for the defaulted index namespace
* Update documentation
* A job has been created to make aggregate MDS population more robust https://github.com/uc-cdis/cloud-automation/pull/1722
=> feat(populate): improved populate script, docs

README.md
- Add test DB creation to readme
=> Add test DB creation to readme

docs/openapi.yaml, src/mds/objects.py, tests/test_objects.py
Jira Ticket: [PXP-9697](https://ctds-planx.atlassian.net/browse/PXP-9697)
* Improving DELETE endpoint for `/objects` API.
=> Improving DELETE endpoint for /objects API.

src/mds/agg_mds/datastore/elasticsearch_dao.py
Jira Ticket: [HP-873](https://ctds-planx.atlassian.net/browse/HP-873)
cherry-picked fix from #55
- Fix agg MDS normalizer to handle dates
=> HP-873 Fix agg MDS normalizer

poetry.lock, pyproject.toml, src/mds/agg_mds/datastore/elasticsearch_dao.py, tests/test_agg_mds_elasticsearch_dao.py
Jira Ticket: [HP-889](https://ctds-planx.atlassian.net/browse/HP-889)
Nested fields are not able to be normalized in elastic search. Adding pydash to set items in nested fields.
adding pydash to poetry
=> HP-889 adding normalization nesting for date

docs/openapi.yaml, poetry.lock, pyproject.toml
=> Bumping version of MDS

docs/openapi.yaml, pyproject.toml
=> chore(version): bump

.secrets.baseline, README.md, docs/agg_mds.md, docs/dev.md
- Documentation: add details about what MDS is, what Aggregate MDS is, and reorganize the documentation
=> Reorganize docs

src/mds/agg_mds/adapters.py, src/mds/populate.py
Jira Ticket: [BRH-323](https://ctds-planx.atlassian.net/browse/BRH-323)
* Increasing wait time for an aggregated MDS response to handle commons that take longer than the default 5 seconds to load.
* Adding a Null Check for tags in an entry in the aggregated response.
=> (BRH-323): Time-Out Error in MIDRC

src/mds/objects.py
- Log detailed authentication errors from authutils
=> Log detailed authentication errors from authutils

src/mds/objects.py
=> update token aud

src/mds/agg_mds/adapters.py, tests/test_agg_mds_windber_adapter.py
Link to JIRA ticket if there is one: n/a
- getting tags in Windber adapter
=> fix: Windber adapter dictionary issue

src/mds/admin_login.py
Link to JIRA ticket if there is one: 
- Add logs to admin authorization logic
=> Add logs to admin authz logic
